// Snapshot of real cat wall products. See README limitation.

export const seedCatalog = [
  {
    id: "frisco-cushioned-wall-shelf",
    sku: "399655",
    name: "Frisco Cushioned Wall Mounted Cat Wall Shelf",
    shortName: "Cushion Shelf",
    type: "shelf",
    model: "frisco-cushion-shelf",
    price: 29.99,
    rating: 4.6,
    reviews: 185,
    width: 15.74,
    depth: 12.2,
    height: 5.9,
    maxLoad: 20,
    material: "wood + removable cushion",
    source: "Chewy",
    sourceChecked: "2026-07-07",
    imageUrl: "https://image.chewy.com/catalog/general/images/frisco-cushioned-wall-mounted-cat-wall-shelf/img-398899._AC_SX500_SY400_QL75_V1_.jpg",
    url: "https://www.chewy.com/frisco-cushioned-wall-mounted-cat/dp/399655"
  },
  {
    id: "frisco-acrylic-bowl-wall-shelf",
    sku: "399651",
    name: "Frisco Acrylic Bowl Wall Mounted Cat Wall Shelf",
    shortName: "Acrylic Bowl",
    type: "hideout",
    model: "frisco-acrylic-bowl",
    price: 52.59,
    rating: 4.5,
    reviews: 90,
    width: 18,
    depth: 15.75,
    height: 6,
    maxLoad: 20,
    material: "wood shelf + acrylic bowl + sisal mats",
    source: "Chewy",
    sourceChecked: "2026-07-07",
    imageUrl: "https://image.chewy.com/catalog/general/images/frisco-acrylic-bowl-wall-mounted-cat-wall-shelf/img-738262._AC_SX500_SY400_QL75_V1_.jpg",
    url: "https://www.chewy.com/frisco-acrylic-bowl-wall-mounted-cat/dp/399651"
  },
  {
    id: "frisco-cat-silhouette-bridge-set",
    sku: "399653",
    name: "Frisco Cat Silhouette with Bridge Wall Mounted Shelves",
    shortName: "Bridge Set",
    type: "bridge",
    model: "frisco-silhouette-bridge",
    price: 66.29,
    rating: 4.4,
    reviews: 86,
    width: 52,
    depth: 9.65,
    height: 16,
    maxLoad: 20,
    material: "wood cubbies + chenille bridge + sisal mats",
    source: "Chewy",
    sourceChecked: "2026-07-07",
    imageUrl: "https://image.chewy.com/catalog/general/images/frisco-cat-silhouette-with-bridge-wall-mounted-cat-wall-shelves/img-357348._AC_SX500_SY400_QL75_V1_.jpg",
    packageParts: [
      { name: "Frisco Cat Silhouette Left Cubby", shortName: "Left Cubby", type: "hideout", model: "frisco-silhouette-cubby", width: 14, depth: 9.65, height: 16, offsetX: 0, offsetY: 0 },
      { name: "Frisco Cat Silhouette Bridge Span", shortName: "Bridge Span", type: "bridge", model: "frisco-silhouette-bridge-span", width: 28, depth: 8, height: 4, offsetX: 12, offsetY: 5 },
      { name: "Frisco Cat Silhouette Right Cubby", shortName: "Right Cubby", type: "hideout", model: "frisco-silhouette-cubby", width: 14, depth: 9.65, height: 16, offsetX: 38, offsetY: 0 }
    ],
    url: "https://www.chewy.com/frisco-cat-silhouette-bridge-wall/dp/399653"
  },
  {
    id: "frisco-wall-mounted-cat-steps",
    sku: "2191294",
    name: "Frisco Wall Mounted Cat Steps, 4 pack",
    shortName: "Step Pack",
    type: "shelf",
    model: "frisco-four-steps",
    price: 29.99,
    rating: 4.5,
    reviews: 31,
    width: 34,
    depth: 8,
    height: 22,
    maxLoad: 15,
    material: "wood + sisal mats",
    source: "Chewy",
    sourceChecked: "2026-07-07",
    imageUrl: "https://image.chewy.com/catalog/general/images/moe/068f1538-172d-77cc-8000-b0de790f1b1e._AC_SX500_SY400_QL75_V1_.jpg",
    packageParts: [
      { name: "Frisco Wall Mounted Cat Step 1", shortName: "Step 1", type: "shelf", model: "frisco-single-step", width: 8, depth: 8, height: 2.5, offsetX: 0, offsetY: 0 },
      { name: "Frisco Wall Mounted Cat Step 2", shortName: "Step 2", type: "shelf", model: "frisco-single-step", width: 8, depth: 8, height: 2.5, offsetX: 9, offsetY: 6 },
      { name: "Frisco Wall Mounted Cat Step 3", shortName: "Step 3", type: "shelf", model: "frisco-single-step", width: 8, depth: 8, height: 2.5, offsetX: 18, offsetY: 12 },
      { name: "Frisco Wall Mounted Cat Step 4", shortName: "Step 4", type: "shelf", model: "frisco-single-step", width: 8, depth: 8, height: 2.5, offsetX: 27, offsetY: 18 }
    ],
    url: "https://www.chewy.com/frisco-wall-mounted-cat-steps/dp/2191294"
  },
  {
    id: "refined-feline-lotus-leaf-shelf",
    sku: "284856",
    name: "The Refined Feline Lotus Leaf Wall Mounted Shelf",
    shortName: "Lotus Leaf",
    type: "shelf",
    model: "lotus-leaf",
    price: 79.99,
    rating: 4.8,
    reviews: 50,
    width: 22,
    depth: 10.5,
    height: 9,
    maxLoad: null,
    material: "bent ply + solid wood + carpet pad",
    source: "Chewy",
    sourceChecked: "2026-07-07",
    imageUrl: "https://image.chewy.com/is/image/catalog/258402_MAIN._AC_SX500_SY400_QL75_V1603403789_.jpg",
    url: "https://www.chewy.com/refined-feline-lotus-leaf-wall/dp/284856"
  },
  {
    id: "armarkat-real-wood-wall-additions",
    sku: "515630",
    name: "Armarkat Real Wood Cat Wall Additions, 2 count",
    shortName: "Armarkat 2-Level",
    type: "hideout",
    model: "armarkat-two-level",
    price: 74.25,
    rating: 4.4,
    reviews: 367,
    width: 20,
    depth: 12,
    height: 18,
    maxLoad: null,
    material: "solid poplar + removable mats",
    source: "Chewy",
    sourceChecked: "2026-07-07",
    imageUrl: "https://image.chewy.com/catalog/general/images/armarkat-real-wood-cat-wall-additions-natural-beige-2-count/img-305064._AC_SX500_SY400_QL75_V1_.jpg",
    packageParts: [
      { name: "Armarkat Real Wood Lower Shelf", shortName: "Lower Shelf", type: "shelf", model: "armarkat-single-shelf", width: 20, depth: 12, height: 3, offsetX: 0, offsetY: 0 },
      { name: "Armarkat Real Wood Upper Shelf", shortName: "Upper Shelf", type: "shelf", model: "armarkat-single-shelf", width: 20, depth: 12, height: 3, offsetX: 0, offsetY: 12 }
    ],
    url: "https://www.chewy.com/armarkat-real-wood-cat-wall-additions/dp/515630"
  },
  {
    id: "pawhut-10-level-wall-shelves",
    sku: "1621678",
    name: "PawHut 10 Level Wood Wall Mounted Cat Shelves",
    shortName: "PawHut 10-Level",
    type: "hideout",
    model: "pawhut-10-level",
    price: 124.99,
    rating: 4.8,
    reviews: 10,
    width: 15.75,
    depth: 12.75,
    height: 17.75,
    maxLoad: null,
    material: "wood + washable pads + cushioned house",
    source: "Chewy",
    sourceChecked: "2026-07-07",
    imageUrl: "https://image.chewy.com/catalog/general/images/moe/0678567f-c213-75ad-8000-aed7bb533482._AC_SX500_SY400_QL75_V1_.jpg",
    packageParts: [
      { name: "PawHut Cushioned House", shortName: "House", type: "hideout", model: "pawhut-house", width: 12, depth: 12.75, height: 8, offsetX: 2, offsetY: 0 },
      { name: "PawHut Step 1", shortName: "Step 1", type: "shelf", model: "pawhut-step", width: 7, depth: 8, height: 1.8, offsetX: 0, offsetY: 7 },
      { name: "PawHut Step 2", shortName: "Step 2", type: "shelf", model: "pawhut-step", width: 7, depth: 8, height: 1.8, offsetX: 9, offsetY: 8.5 },
      { name: "PawHut Step 3", shortName: "Step 3", type: "shelf", model: "pawhut-step", width: 7, depth: 8, height: 1.8, offsetX: 0, offsetY: 10 },
      { name: "PawHut Step 4", shortName: "Step 4", type: "shelf", model: "pawhut-step", width: 7, depth: 8, height: 1.8, offsetX: 9, offsetY: 11.5 },
      { name: "PawHut Step 5", shortName: "Step 5", type: "shelf", model: "pawhut-step", width: 7, depth: 8, height: 1.8, offsetX: 0, offsetY: 13 },
      { name: "PawHut Step 6", shortName: "Step 6", type: "shelf", model: "pawhut-step", width: 7, depth: 8, height: 1.8, offsetX: 9, offsetY: 14.5 },
      { name: "PawHut Step 7", shortName: "Step 7", type: "shelf", model: "pawhut-step", width: 7, depth: 8, height: 1.8, offsetX: 0, offsetY: 16 },
      { name: "PawHut Step 8", shortName: "Step 8", type: "shelf", model: "pawhut-step", width: 7, depth: 8, height: 1.8, offsetX: 9, offsetY: 17.5 },
      { name: "PawHut Top Pad", shortName: "Top Pad", type: "shelf", model: "pawhut-step", width: 12, depth: 10, height: 2, offsetX: 2, offsetY: 19 }
    ],
    url: "https://www.chewy.com/pawhut-10-level-wood-wall-mounted-cat/dp/1621678"
  },
  {
    id: "trixie-wall-set-1-post-perch",
    sku: "822382",
    name: "TRIXIE Wall Set 1 Scratching Post with Perch",
    shortName: "TRIXIE Post",
    type: "scratcher",
    model: "trixie-post-perch",
    price: 40.99,
    rating: 3.5,
    reviews: 28,
    width: 13.8,
    depth: 9.8,
    height: 51.2,
    maxLoad: 15,
    material: "sisal post + jumping platform",
    source: "Chewy",
    sourceChecked: "2026-07-07",
    imageUrl: "https://image.chewy.com/catalog/general/images/trixie-wall-set-1-wall-mount-cat-scratching-post-with-perch-natural-white/img-162427._AC_SX500_SY400_QL75_V1_.jpg",
    url: "https://www.chewy.com/trixie-wall-set-1-wall-mount-cat/dp/822382"
  }
];
